version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/chatbot-angular"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/Backend&Algorithms"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10