#!/usr/bin/env bash
# ============================================================================
#  configure.sh — Personal Financial Tracker · LLM Configuration
# ============================================================================
#  Choose between local GPU (Ollama) or cloud API (OpenAI / Groq).
#  Generates a .env file with the selected configuration.
#  Usage:  chmod +x configure.sh && ./configure.sh
# ============================================================================
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"
BACKEND_DIR="$ROOT_DIR/Backend&Algorithms"
VENV_DIR="$BACKEND_DIR/venv"

# ── Colors ─────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

ok()   { echo -e "${GREEN}✔ $1${NC}"; }
info() { echo -e "${CYAN}▸ $1${NC}"; }
warn() { echo -e "${YELLOW}⚠ $1${NC}"; }
fail() { echo -e "${RED}✖ $1${NC}"; exit 1; }

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   🔧 Personal Financial Tracker — LLM Configuration    ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# ── Show current config if exists ──────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}Configuración actual:${NC}"
    grep -E "^LLM_" "$ENV_FILE" 2>/dev/null | while read -r line; do
        echo "  $line"
    done
    echo ""
fi

# ── Ask for mode ───────────────────────────────────────────────────────────
echo -e "${BOLD}¿Cómo quieres ejecutar el modelo de lenguaje (LLM)?${NC}"
echo ""
echo -e "  ${GREEN}1)${NC} 🖥️  GPU Local (Ollama) — Requiere GPU NVIDIA + Ollama instalado"
echo -e "  ${GREEN}2)${NC} ☁️  OpenAI API         — Requiere API key de OpenAI"
echo -e "  ${GREEN}3)${NC} ⚡ Groq API           — Requiere API key de Groq (gratis)"
echo ""
read -rp "$(echo -e "${CYAN}Selecciona [1/2/3]:${NC} ")" choice

case "$choice" in
    1)
        LLM_MODE="ollama"
        echo ""
        info "Modo seleccionado: GPU Local (Ollama)"

        # Check Ollama is installed
        if ! command -v ollama &>/dev/null; then
            fail "Ollama no está instalado. Instálalo desde https://ollama.com"
        fi

        # Ask for model
        echo ""
        read -rp "$(echo -e "${CYAN}Modelo a usar (default: llama3.2:3b):${NC} ")" model_input
        LLM_MODEL="${model_input:-llama3.2:3b}"

        # Check if Ollama is running and pull model
        info "Verificando modelo $LLM_MODEL..."
        if curl -s http://localhost:11434/api/tags >/dev/null 2>&1; then
            if ! ollama list 2>/dev/null | grep -q "$LLM_MODEL"; then
                info "Descargando modelo $LLM_MODEL..."
                ollama pull "$LLM_MODEL"
            fi
            ok "Modelo $LLM_MODEL disponible"
        else
            warn "Ollama no está corriendo. Ejecuta 'ollama serve' antes de iniciar."
        fi

        # Write .env
        cat > "$ENV_FILE" <<EOF
# Personal Financial Tracker — LLM Configuration
# Generated by configure.sh on $(date '+%Y-%m-%d %H:%M')
LLM_MODE=ollama
LLM_MODEL=$LLM_MODEL
EOF
        ;;

    2)
        LLM_MODE="openai"
        echo ""
        info "Modo seleccionado: OpenAI API"

        # Ask for API key
        echo ""
        read -rp "$(echo -e "${CYAN}Ingresa tu API key de OpenAI:${NC} ")" api_key
        [ -z "$api_key" ] && fail "API key no puede estar vacía"

        # Ask for model
        read -rp "$(echo -e "${CYAN}Modelo a usar (default: gpt-4o-mini):${NC} ")" model_input
        LLM_MODEL="${model_input:-gpt-4o-mini}"

        # Install openai if not present
        if [ -d "$VENV_DIR" ]; then
            info "Instalando dependencia 'openai'..."
            source "$VENV_DIR/bin/activate"
            pip install openai python-dotenv -q
            ok "openai instalado"
        fi

        # Write .env
        cat > "$ENV_FILE" <<EOF
# Personal Financial Tracker — LLM Configuration
# Generated by configure.sh on $(date '+%Y-%m-%d %H:%M')
LLM_MODE=openai
LLM_MODEL=$LLM_MODEL
OPENAI_API_KEY=$api_key
EOF
        ;;

    3)
        LLM_MODE="groq"
        echo ""
        info "Modo seleccionado: Groq API"

        # Ask for API key
        echo ""
        echo -e "  ${YELLOW}Obtén tu API key gratis en: https://console.groq.com/keys${NC}"
        read -rp "$(echo -e "${CYAN}Ingresa tu API key de Groq:${NC} ")" api_key
        [ -z "$api_key" ] && fail "API key no puede estar vacía"

        # Ask for model
        read -rp "$(echo -e "${CYAN}Modelo a usar (default: llama-3.1-8b-instant):${NC} ")" model_input
        LLM_MODEL="${model_input:-llama-3.1-8b-instant}"

        # Install groq if not present
        if [ -d "$VENV_DIR" ]; then
            info "Instalando dependencia 'groq'..."
            source "$VENV_DIR/bin/activate"
            pip install groq python-dotenv -q
            ok "groq instalado"
        fi

        # Write .env
        cat > "$ENV_FILE" <<EOF
# Personal Financial Tracker — LLM Configuration
# Generated by configure.sh on $(date '+%Y-%m-%d %H:%M')
LLM_MODE=groq
LLM_MODEL=$LLM_MODEL
GROQ_API_KEY=$api_key
EOF
        ;;

    *)
        fail "Opción inválida. Usa 1, 2 o 3."
        ;;
esac

# ── Protect .env permissions ───────────────────────────────────────────────
chmod 600 "$ENV_FILE"

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   ✅  Configuración guardada en .env                    ║${NC}"
echo -e "${GREEN}║                                                         ║${NC}"
echo -e "${GREEN}║   Modo:   $LLM_MODE$(printf '%*s' $((42 - ${#LLM_MODE})) '')║${NC}"
echo -e "${GREEN}║   Modelo: $LLM_MODEL$(printf '%*s' $((42 - ${#LLM_MODEL})) '')║${NC}"
echo -e "${GREEN}║                                                         ║${NC}"
echo -e "${GREEN}║   Para cambiar: ./configure.sh                          ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
